version: '3'

services:
  rancher:
    image: rancher/rancher:latest
    restart: unless-stopped
    privileged: true
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - rancher:/var/lib/rancher

volumes:
  rancher:
